spring:
  datasource:
    url: jdbc:mysql://47.95.223.172:3306/juntai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Admin1234.
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090

mybatis:
  type-aliases-package: cn.edu.guet.weapp_SpringBoot.bean
  mapper-locations: classpath:mapper/*Mapper.xml
# mapper-locations: classpath:mapper/*.Mapper.xml


